name: Linux

on:
  push:
    branches: [ master, '*-ci' ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build_linux:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: ["ubuntu-20.04", "ubuntu-22.04"]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install Grpc library
      uses: eWaterCycle/setup-grpc@v5
      with:
        grpc-version: 1.43.0

    - name: Build Zserio C++ Service Grpc
      run: |
        mkdir build
        cd build
        cmake ../examples/calculator -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=../distr
        cmake --build . --target install

    - name: Test Zserio C++ Service Grpc
      run: |
        cd build
        ./CalculatorServer &
        sleep 10
        echo -e "p\\n100\\nq" | ./CalculatorClient | grep "10000"
        echo -e "s\\n100\\nq" | ./CalculatorClient | grep "10"
        kill $(jobs -p)

    - name: Archive Zserio C++ Service Grpc binaries
      uses: actions/upload-artifact@v3
      with:
        name: zserio-service-grpc-cpp-${{matrix.os}}
        path: distr/*
